baseURL = "http://ignaciodenuevo.com/"
title = "Ignacio Villanueva - Front-end developer, author, podcaster and speaker."
description = "Articles on front-end developer focused on architecture, front-end performance and responsive web design."
name = "Ignacio Villanueva"
email = "ignaciodenuevo@gmail.com"
twitter = "https://twitter.com/ignaciodenuevo"
github = "https://github.com/ignaciodenuevo"
rrss = "IgnaciodeNuevo"
language = "en"
theme = "next"
